### ISSUE TITLE
Use with oculus quest

### ISSUE THREAD

**Issue by jpike88** [SimulaVR/Simula#100]
Is this possible? I know the resolution isn't top notch but if it's not hard to support it, that would get more people tinkering with it

**Comment by lboklin** [comment]
Oculus Quest does not provide any drivers for Linux and as Simula is Linux-exclusive this is not a possibility until a driver becomes available.

**Comment by SanderVocke** [comment]
I'd like to point out that it is possible to run a limited Linux distro inside an Oculus Quest or Oculus Quest 2 via PRoot (e.g. via the Termux terminal emulator app). And Godot supports Android. So to me it sounds like the absolute necessities are there, although there would be a lot of work left to do.

**Comment by whitewhidow** [comment]
just to add here,    if immersedvr can do it,   that means its possible ...   no ?   (they are expensive as fuck)

**Comment by kevrat** [comment]
+1

**Comment by rmortes** [comment]
I haven't done any VR development yet, so I don't know what I'm talking about, but why exactly can't we use SImula with a Quest or Quest2? I've succesfully player SteamVR games wirelessly using ALVR, so why can't I run SImula in the same fashion?

**Comment by jonashrem** [comment]
maybe WSL is an option?
