### ISSUE TITLE
Oculus VR support?

### ISSUE THREAD

**Issue by kauegimenes** [SimulaVR/Simula#101]
Any plans for Oculus Rift S support? 

What about macOS?

Thanks

**Comment by KaneTW** [comment]
Any HMD that's supported by OpenVR/SteamVR (on Linux) will work. We don't have access to an Oculus, so no idea if it's supported.

**Comment by KaneTW** [comment]
There might be bugs due to some implicit assumptions that are only true on HTC Vive/Index/etc, but that's easily fixable. SteamVR support is the big issue.

**Comment by lboklin** [comment]
There will simply not be any support for any oculus product until they release drivers for Linux. MacOS does not use or support the Wayland display protocol so unless that changes it will also not be possible.

**Comment by lboklin** [comment]
Regarding assumptions about the Vive hardware in the code, it should not be too much work to abstract it.
