### ISSUE TITLE
What is the license of the project?

### ISSUE THREAD

**Issue by sharpaper** [SimulaVR/Simula#104]

**Comment by KaneTW** [comment]
https://github.com/SimulaVR/Simula/blob/gdwlroots-xwayland/addons/godot-haskell-plugin/LICENSE

**Comment by KaneTW** [comment]
We'll move it to top folder and change it to MIT I think

**Comment by georgewsinger** [comment]
We just added the MIT License to the project.  See https://github.com/SimulaVR/Simula/blob/gdwlroots-xwayland/LICENSE
