### ISSUE TITLE
Releasing "super" before "alt" results in window continuing to follow gaze.

### ISSUE THREAD

**Issue by gmorenz** [SimulaVR/Simula#109]
After pressing super-alt the window follows my gaze until I release alt while super is still pressed. If I release super and then alt the window follows my gaze "forever" (until I repress super+alt and release alt before releasing super).

**Comment by georgewsinger** [comment]
Thanks for bringing this to our attention. It has been fixed in our latest commit.  To use run

```
git pull origin gdwlroots-xwayland
source ./utils/Helpers.sh && installSimula
```

or reclone/reinstall. If you see any other issues preventing you from getting utility out of Simula, let me know!
