### ISSUE TITLE
Align modal windows with parent window

### ISSUE THREAD

**Issue by danielfullmer** [SimulaVR/Simula#111]
Example here:
![simulavr](https://user-images.githubusercontent.com/1298344/79292914-51c5b500-7ea0-11ea-8308-dc12316f6103.jpg)

It would be better if modal windows were aligned with their parent window. If possible, this would help usability a lot. Applying a small offset from the parent window could be nice to experiment with for a 3D effect.

**Comment by georgewsinger** [comment]
We're making progress on this issue:

![image](https://user-images.githubusercontent.com/10677444/80292573-3d49ae00-8725-11ea-89a4-eb7200156935.png)

Should be fixed by end of weekend!

**Comment by georgewsinger** [comment]
:heavy_check_mark: Fixed in latest commit. To pull it run

```
git pull origin gdwlroots-xwayland
source ./utils/Helpers.sh && installSimula
./result/bin/simula
```

**Comment by georgewsinger** [comment]
@danielfullmer  I recently pushed the dhall config to our repo. Per your request: it includes fields for setting default window resolution and scale. That said, I'm recently experiencing errors in NixOS. Specifically, chrome popups seem to no longer work for me (though they still work in non-NixOS). Did you ever confirm that chrome popups worked for you in NixOS?

**Comment by danielfullmer** [comment]
Yes, the chrome popups have been constrained to the original window for me in the past. I just verified it still has that behavior in the latest commit.

However, I just noticed this: 
![chrome](https://user-images.githubusercontent.com/1298344/82742770-28663780-9d30-11ea-81ff-e48cbd7f76fd.png)
It might require zooming in, but notice how the selected option "History" creates another modal window to the right of it. But, most of this is cut off by the edge of the window.

**Comment by georgewsinger** [comment]
@danielfullmer We're working on a solution now to push popups that hang over window boundaries back inside the window.  Once it's pushed I'll update this thread.

**Comment by georgewsinger** [comment]
@danielfullmer I just pushed a commit which crudely pushes subsurfaces into their parent window boundaries.  There's still some subtle input and subsurface bugs to fix, but I think this is an overall improvement to the behavior.  I'll keep you updated as we push more fixes on this front.
