### ISSUE TITLE
Launching firefox / google-chrome freezes SimulaVR if the program is missing

### ISSUE THREAD

**Issue by danielfullmer** [SimulaVR/Simula#112]
To reproduce:

Ensure `firefox` and/or `google-chrome-bin` is not in `PATH`. Pressing `Super + k` or `Super + g` will lock up SimulaVR. If SimulaVR has grabbed the keyboard/mouse then the only way to recover is to SSH in and kill the process.

This message is produced in the terminal which launched simulavr:
```
libGodotHaskellPlugin.so: google-chrome-stable: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

Running `ps aux | grep godot` gives this:
```
danielrf  15199 10.7  0.7 1076100168 493120 pts/2 Sl+ 18:52   0:02 /nix/store/pv2f42v7a16mz8k20mk4jws4x4633nvp-godot-3.2/bin/godot.x11.opt.debug.64 -m
danielrf  15239  0.3  0.0      0     0 pts/2    Z+   18:52   0:00 [godot.x11.opt.d] <defunct>
```

(I had thought that this was a conflict between my i3 keybinds and simulaVR's but I was incorrect)

**Comment by KaneTW** [comment]
This will likely be fixed once Dhall custom configuration is in.

**Comment by KaneTW** [comment]
Actually, this does remind me: we need to ungrab the keyboard if we crash.

**Comment by georgewsinger** [comment]
We added app launching error handling to our most recent commits.  @KaneTW Do you know how to ungrab keyboard on crash?

**Comment by KaneTW** [comment]
Godot has crash_handler_x11.cpp. It also fires a NOTIFICATION_CRASH event, but that might not help us if we have a Haskell crash.

**Comment by georgewsinger** [comment]
Ok I'll look into those paths.  Closing for now.
