### ISSUE TITLE
Stuttering at 120hz, works fine at 90hz.

### ISSUE THREAD

**Issue by danielfullmer** [SimulaVR/Simula#113]
When running SimulaVR at 120Hz in my Valve Index, I have stuttering roughly once every couple of seconds:
![120hz](https://user-images.githubusercontent.com/1298344/82132193-2a1d8180-97ab-11ea-9081-fbc5bf99d009.png)

If I switch into 90Hz mode and restart SteamVR, then it is perfectly smooth and usable:
![90hz](https://user-images.githubusercontent.com/1298344/82132192-2984eb00-97ab-11ea-9c8e-d9ad75386d5c.png)

I do not have this issue in other apps (e.g SteamVR Home). I doubt this is a result of not having good enough hardware.

System details:
VR Headset: Valve Index
GPU:NVIDIA 1080TI
CPU: 3970x Threadripper + 64GB Memory
Distro: NixOS unstable

**Comment by KaneTW** [comment]
This looks highly abnormal. I don't have an Index available right now (and they're backordered to hell) so I don't know how to test this easily. I'll see what we can do until an Index is available.

**Comment by lboklin** [comment]
I believe the physics is set to 90hz, so it could be something tied to that. Something that shouldn't be in `_physics_process` but is?

**Comment by georgewsinger** [comment]
Not sure if these matter, but the following settings are set to 90:

- [VR target fps](https://github.com/SimulaVR/Simula/blob/48e7c3d76b9eb176b567b8057c8ab2121874d1f3/addons/godot-haskell-plugin/src/Plugin/VR.hs#L61)
- `common/physics_fps=90` in `project.godot`

**Comment by lboklin** [comment]
That setting is what I was referring to, yes

**Comment by danielfullmer** [comment]
Changing this line from 90 to 120 fixes this problem for me:
https://github.com/SimulaVR/Simula/blob/48e7c3d76b9eb176b567b8057c8ab2121874d1f3/addons/godot-haskell-plugin/src/Plugin/VR.hs#L61

The `common/physics_fps=90` in `project.godot` didn't seem to change anything for me.

**Comment by KaneTW** [comment]
We should consider setting that to 0 (no limit) or <HMD refresh rate>

**Comment by georgewsinger** [comment]
@danielfullmer Does changing the setting to 0 also fix the issue for you?

**Comment by danielfullmer** [comment]
Yes, setting to 0 also fixes the issue.  I can also confirm that 144Hz mode in the Valve Index works as well:
![144hz](https://user-images.githubusercontent.com/1298344/82158387-91900b80-9855-11ea-87db-46228ab5c97e.png)

**Comment by georgewsinger** [comment]
Nice catch!  I've changed the code accordingly, and it will be sent to master during our next commit.  (Alternatively, if you send a PR I'll merge it so you can get credit for the fix).

**Comment by danielfullmer** [comment]
Thanks for the help! No worries about credit.
