### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by grizeldi** [SimulaVR/Simula#116]
Trying to install Simula through the guide in README.md on Ubuntu 19.10 and I get stuck at this line: `source ./utils/Helpers.sh && installSimula`. It outputs the following:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
bash: /home/grizeldi/.nix-profile/etc/profile.d/nix.sh: No such file or directory
nix-env: command not found
cachix: command not found

Message from Simula Contributors.
=================================

In order to show project funders that Simula is useful, 
we anonymously collect the following data:

- Session length
- Number of windows active
- Error logs on crashes

nix-build: command not found
```
Looks like missing dependecies, something clearly went wrong.

**Comment by KaneTW** [comment]
We found the issue, Nix changed their install procedure slightly. Fixing in a moment.

**Comment by georgewsinger** [comment]
:heavy_check_mark: Fixed.

Try recloning/reinstalling and let me know if any problems persist.

**Comment by FictionX** [comment]
Well it's doing.. something... but it's downloading a lot of stuff (maybe the entire NixOS?) and compiling it. It's definitely taking a lot longer than a minute.
It's also asking for sudo to install in /nix. Is it supposed to do that?

Ramdom examples from the terminal:
copying path '/nix/store/v1x8s1j4qq117mw5ps18kv4vcks20kcw-libjack2-1.9.14' from 'https://cache.nixos.org'...
copying path '/nix/store/vlihhl4qxryazhgfc01v4jswnkclb0fw-pcsclite-1.8.26-bin' from 'https://cache.nixos.org'...
copying path '/nix/store/bd3xj2p79zrqkz9xr8daq6752avvv90f-stdenv-linux' from 'https://cache.nixos.org'...
copying path '/nix/store/riagsp19ly9fya2ylxj6zw53djk3malv-pcsclite-1.8.26' from 'https://cache.nixos.org'...
copying path '/nix/store/1azn3iigi188zx9f1fq7y6hqnwnkxqlx-v4l-utils-1.18.0' from 'https://cache.nixos.org'...
copying path '/nix/store/dyici3b7gzrg9gyjzlh3ix7xg0nmzpbi-zlib-0.6.2.1-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/fgi7xhmh3hs2v5pzq2k8r4kw22h9yy9g-zlib-1.2.11' from 'https://cache.nixos.org'...
copying path '/nix/store/ss1q0fwd36w1bkx3wikv3ljhqxar29w5-streaming-commons-0.2.1.2-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/nfs9wf6ipffr9g9ylzb4i9c1i607nxvq-binutils-2.31.1' from 'https://cache.nixos.org'...
copying path '/nix/store/pfsisadn42a4c8m760sqj6p9yp1ardkc-cracklib-2.9.7' from 'https://cache.nixos.org'...

[Initial build] Compiling ==> thirdparty/assimp/code/FBX/FBXMaterial.cpp
[Initial build] Compiling ==> thirdparty/assimp/code/FBX/FBXMeshGeometry.cpp
[Initial build] Compiling ==> thirdparty/assimp/code/FBX/FBXModel.cpp
[Initial build] Compiling ==> thirdparty/assimp/code/FBX/FBXNodeAttribute.cpp
[Initial build] Compiling ==> thirdparty/assimp/code/FBX/FBXParser.cpp
[Initial build] Compiling ==> thirdparty/assimp/code/FBX/FBXProperties.cpp
[Initial build] Compiling ==> thirdparty/assimp/code/FBX/FBXTokenizer.cpp

(I didn't let it finish)

**Comment by georgewsinger** [comment]
The way our build system works is:

1. First it tries to download all nix dependencies from cachix (a service that stores nix dependencies in the cloud; should take ~1 minute on a good internet connection).
2. If (1) fails, it builds Simula from scratch with nix (which takes like 1hr+).

It looks like (2) is what is happening.  Let me look into our cachix system to make sure it is working.

**Comment by georgewsinger** [comment]
The issue should be fixed (I stupidly forgot to upload the last change to cachix :crying_cat_face: ).  Try recloning/reinstalling.

**Comment by FictionX** [comment]
I'm afraid it's still creating /nix and downloading the whole thing.
Is there a log or anything I can provide?

**Comment by georgewsinger** [comment]
Can you paste/upload the first part of the compilation (before Godot starts downloading)?

**Comment by FictionX** [comment]
I'm not sure when it starts compiling Godot..
Is this useable? : https://pastebin.com/rrWVqCcQ

**Comment by georgewsinger** [comment]
Can you check if `cachix` was successfully installed on your system (e.g. does `cachix --help` show anything)?

**Comment by FictionX** [comment]
Yes - it's there.

**Comment by georgewsinger** [comment]
I'm trying a fresh install on another machine. Will see if I can duplicate this.

**Comment by georgewsinger** [comment]
I'm so far unable to duplicate this on other machines. Hmm.  Can you tell me the output of `nix --version` and `cachix --version`?  It might be a good idea to version match against your system.

Also: what distro are you running?

**Comment by FictionX** [comment]
nix (Nix) 2.3.6
cachix 0.3.8

I cloned it again like I did between every retry - but now it works! I'm not sure what went wrong.
Sorry for the trouble!

**Comment by georgewsinger** [comment]
All good. Possibly cachix took a while to receive our payload?

How was your Simula demo? Did you run into any other crashes or weird behavior?

**Comment by FictionX** [comment]
I haven't had time to really test it yet - I just briefly checked that it worked. I wasn't aware that it would take over my keyboard and mouse, and since I hadn't made a note of the shortcuts, I had to do a hard reset to get my Desktop back :-)

I looked fine, though! I look forward to trying it out for real!

**Comment by grizeldi** [comment]
As my original problem has been resolved, I'm closing this issue.
