### ISSUE TITLE
Terminal Transparency Support

### ISSUE THREAD

**Issue by Nikita240** [SimulaVR/Simula#123]
Hi, I'm a self-admitted WM ricer.

What would it take to get transparency support for terminals inside Simula? 

Would be really cool if we could get background blur effects working like in KWin.

**Comment by georgewsinger** [comment]
@Nikita240 Terminals can be made transparent by gazing at them and pressing `Super + Alt + Down` (default binding).  Here's a short video demonstration which shows the effect: https://www.youtube.com/watch?v=rm72Qmi8Bik&t=41s&ab_channel=GeorgeSinger
