### ISSUE TITLE
Steam not supported on Ubuntu 20.04

### ISSUE THREAD

**Issue by Corallus-Caninus** [SimulaVR/Simula#127]
Trying to get Steam installed for Simula and am getting strange errors. Tried both proprietary and open source drivers for NVIDIA. Does anyone else have this issue?

Is Simula currently running on ubuntu 20.04 through steamvr for anyone (is this just my configuration?) 

Thanks I hope to learn more about Simula.

**Comment by KaneTW** [comment]
That's our standard configuration and works fine on our side. Are you having issues with Steam itself?

**Comment by Corallus-Caninus** [comment]
Worked after a (3rd) reboot. just twiddled with NVIDIA drivers vs noveua and i386 installations. Dont know what worked because I tried everything but the last thing was launching from CLI and installing from apt repository after purging from the same repo. I am on noveua drivers now but thats probably not it. (may be getting harassed following a phishy web page by the same name as this issue).
