### ISSUE TITLE
Clipboard doesn't work across apps of different kinds

### ISSUE THREAD

**Issue by Corallus-Caninus** [SimulaVR/Simula#130]
copying to clipboard does not allow pasting in another window. Pasting can only occur within the window that is copied from.

**Comment by georgewsinger** [comment]
Pernosco traces:

- **Rootston trace (success).** Copying the phrase "earn more" from firefox to xfce4-terminal successfullly: [link](https://pernos.co/debug/LA9v2i3dLfvvsFQJNDh49Q/index.html)
- **Simula trace (failure).** Attempting and failing to copy the phrase "Sorry" from firefox to xfce4-terminal: [link](https://pernos.co/debug/56C86TAmrvVQ6Afq72xj6A/index.html)

**Comment by georgewsinger** [comment]
:heavy_check_mark: @Corallus-Caninus Fixed in https://github.com/SimulaVR/Simula/commit/e4b661286dfcddef76207d3ca8066e0f8db93412, and now merged with master.
