### ISSUE TITLE
GUI extract on zip files causes window to lockup with no additional window popup

### ISSUE THREAD

**Issue by Corallus-Caninus** [SimulaVR/Simula#133]
Trying to extract a zip from the GUI causes the window to lock. I suspect this is due to not handling the sub window file explorer popup. Window does not respond to kill (super+backspace) signal presumably due to phantom sub window focus.

Steps taken to reproduce:
1. Download a zip from Firefox and open.
2. click extract in the window that pops up.

**Comment by georgewsinger** [comment]
**Video replication of bug.** I'm able to replicate this bug in Simula, but not in rootston (our reference compositor that we use for learning purposes).  Here's a video: https://youtu.be/HT4WBk7Teo8

:hourglass_flowing_sand: Making Pernosco traces now for us to study.

**Comment by georgewsinger** [comment]
We've been fighting through some bugs to get our traces working.  Here's [Rootston.FirefoxUnzipExtract](https://pernos.co/debug/9QOCFtBHG4nHIoNegNOIGg/index.html) which might provide some insight.  Still need to sort through some things to get a Simula trace.  After that, what's causing this bug should be pretty apparent in the comparison between the two traces.

**Comment by georgewsinger** [comment]
We were able to get [Simula.FirefoxUnzipExtract](https://pernos.co/debug/IUICfRX3qxxVggaxRq5PQA/index.html) up and running, so now have the ability to compare the working vs. non-working traces.

**Comment by georgewsinger** [comment]
:heavy_check_mark: Fixed in https://github.com/SimulaVR/Simula/commit/92ae71d83780e59c5b32e04d7ec8874fd3190f05 on `dev` branch. @Corallus-Caninus
