### ISSUE TITLE
README.md has deprecated update instructions

### ISSUE THREAD

**Issue by Corallus-Caninus** [SimulaVR/Simula#135]
instructions to update Simula are not reproducible on Ubuntu 20.04. Does the Nix/Cachix runtime check automatically update now?

**Comment by georgewsinger** [comment]
Were you on `master` or `dev` branch when you tried to update?  Did it build but fail to launch, or did it not build anything at all?

Here's our current command for reference:

```sh
updateSimula() {    checkInstallNix    checkInstallCachix    cachix use simula
    if [ -z $1 ]; then        git pull origin master        NIXPKGS_ALLOW_UNFREE=1 nix-build -Q default.nix --arg onNixOS "$(checkIfNixOS)" --arg devBuild "false"    else        switchToNix        git pull origin dev        NIXPKGS_ALLOW_UNFREE=1 nix-build -Q -K default.nix --arg onNixOS "$(checkIfNixOS)" --arg devBuild "true"        switchToLocal    fi}
```

**Comment by georgewsinger** [comment]
The issue (I think) was that our `updateSimula()` shell command wasn't updating git submodules.  Fixed in https://github.com/SimulaVR/Simula/commit/a88f9dbf7ccaef704bfad29cfd6e571241d68da9 and pushed to master.

LMK if this doesn't fix the issue, and I'll reopen.

**Comment by Corallus-Caninus** [comment]
This is completely my fault.

I cancelled a build when cachix/nix failed for my plat and somehow got Simula to run anyways. Allowing installSimula to complete created the updateSimula.sh script for me and I cannot reproduce this anymore. (I didn't have updateSImula.sh at all)

**Comment by georgewsinger** [comment]
No worries. A fail safe way to update is just to reclone/re-run the install command:

```
git clone --recursive https://github.com/SimulaVR/Simula SimulaUpdate
cd SimulaUpdate
source ./utils/Helpers.sh && installSimula
```

This is less convenient than running `updateSimula`, but it should always work :]
