### ISSUE TITLE
doesn't build on ubuntu 20

### ISSUE THREAD

**Issue by Corallus-Caninus** [SimulaVR/Simula#162]
following the instructions in the Readme fails outright on ubuntu. I have also tried installing manually the dependencies but either way it want build with various errors from nix. (everything from dependency to macro expansions). please let me know how I can add more information but the bug should be reproducible on a vanilla Ubuntu container.

**Comment by Corallus-Caninus** [comment]
This was on both dev and master I tried both.

**Comment by georgewsinger** [comment]
Can you paste the compilation error?

**Comment by georgewsinger** [comment]
@Corallus-Caninus I just fixed a `dev` branch issue that might have fixed things on that branch.

As for master branch, there might be an issue with nvidia cards.  Looking into it now.

**Comment by Corallus-Caninus** [comment]
Just tried this again on master and triggered a compilation (which fails with cc errors). Will try on dev branch later today. I'm going to dedicate some time to this I'm set on getting my HP reverb g2 running with monado (comparable resolution to simula one, don't have the cash to buy atm but is the next best device in my opinion).

**Comment by Corallus-Caninus** [comment]
Ubuntu jammy triggers a build on dev but finishes. I got SimulaVR to splash and now am wrestling with Monado.

...Scruffy believes in this company.

**Comment by Corallus-Caninus** [comment]
vanilla Monado runs and I am able to get into Simula. I have some rotational drift but that may be due to monado or some other issues.

in conclusion: dev branch and following the monado directions on the README after running sudo monado-service launches correctly. I have to unplug and plug in the headset after running monado otherwise GTK gets confused with display selection and I get a compositor init_swapchain error.
