### ISSUE TITLE
Simula uses a high pass filter not a low pass filter

### ISSUE THREAD

**Issue by johnblommers** [SimulaVR/Simula#164]
A nit to be sure but I believe Simula uses a high-pass filter to sharpen text, not a low-pass filter. A low-pass filter would blur features.

**Comment by KaneTW** [comment]
It's a low pass. A highpass would remove low-spatial-frequency features, e.g. you wouldn't be able to differentiate between a white menu bar and a black background; you would just see the line. 

A lowpass removes high-spatial-frequency features such as noise and sampling artifacts, which is exactly what happens here.

We apply a Kaiser window, which has the following example frequency domain:
![image](https://user-images.githubusercontent.com/8109607/140592366-cc0690da-b819-41fc-8b07-a88759195b53.png)

As you can see, it's clearly a lowpass.
