### ISSUE TITLE
Get rid of X11

### ISSUE THREAD

**Issue by iMonZ** [SimulaVR/Simula#166]
Which of the following tools are enabled by default?

**Comment by KaneTW** [comment]
X11 should be the default (things will break on wayland i'm pretty sure). No idea about audio, we don't use it internally.

**Comment by iMonZ** [comment]
> X11 should be the default (things will break on wayland i'm pretty sure). No idea about audio, we don't use it internally.

Oh that’s sad.
Is there a plan to get rid of X11?

**Comment by KaneTW** [comment]
Not until VR works well under Wayland.
