### ISSUE TITLE
Install script hangs on Ubuntu 20.04

### ISSUE THREAD

**Issue by robincafolla** [SimulaVR/Simula#168]
Following install instructions on Ubuntu 20.04.

The command `source ./utils/Helpers.sh && installSimula` outputs the following and just hangs:

```
Message from Simula Contributors.
=================================

In order to show project funders that Simula is useful, 
we anonymously collect the following data:

- Session length
- Number of windows active
- Error logs on crashes
```

**Comment by KaneTW** [comment]
Doesn't actually hang. It's just downloading nixpkgs.

**Comment by robincafolla** [comment]
Not a regular user of nix, but shouldn't there be some output from it? If nothing else you should probably add a message saying `Downloading nixpkgs, this will take a while`. 

I think I left it running for about 30 min on fast broadband and it didn't progress, so I assumed it had hung.

**Comment by KaneTW** [comment]
Good idea. It's definitely a bit of a nonstandard use so some indication would be nice
