### ISSUE TITLE
The configured/default backend 'OpenXR' doesn't match the expectations set forth in README.org

### ISSUE THREAD

**Issue by kallistisoft** [SimulaVR/Simula#170]
**Reading the documentation gives the impression that the default backend is OpenVR:**
- The instructions for starting simula mention that SteamVR needs to be running
- The section on the OpenXR backend is explicitly labeled as 'optional'.

**In actuality the default backed configured in the '/config/config.dahll' file is OpenXR**
`line 10:  {   _backend = "OpenXR" -- Supported options: "OpenVR", "OpenXR"`

**I really think this should be changed to OpenVR so it matches the documentation.**

I'd submit a pull request but that seems overly complicated for a one-letter change ;)

**Comment by ViktorWalter** [comment]
I agree with this suggestion - it took me a really long time to figure out why the instructions don't work.

**Comment by graysonhead** [comment]
I also had difficulty with this.

**Comment by KaneTW** [comment]
Fixed it. Sorry about keeping it unfixed for a year.
