### ISSUE TITLE
The Project is Awesome

### ISSUE THREAD

**Issue by jeff-hykin** [SimulaVR/Simula#177]
I wanted to mention, since I don't think most people will, using nix is a game changer. At least for me in terms of buying the Simula headset.

I looked at the headset several months ago, came back today to look into the details/progress. I loved the idea, but had reservations about SimulaOS. I heavily assumed it would be like any decent Linux derivative, like SteamOS.  I loved that Valve made SteamOS based on Arch, but couldn't help but feel sad. Sad because I knew packages for apt and pacman (and most other package managers) are extremely vulnerable to bitrot, and come with system caveats. They work ...if you have libiconv, or gcc, or pull the lastest driver, or set some ENV var. If I'm going to depend on something, or dump time into contributing, I need to know it's going to work; no bitrot, no caveats.

So, seeing this project use nix (and use it well!) puts it in a completely different category. Progress here is permanent. Even if there haven't been commits in a while, I don't have any reservations making my workflow heavily depend on Simula. I really didn't expect the niche community of Linux VR desktop users to also overlap with reliable-code enthusiasts.

(Also I'm going to have to look at cachix for my projects. I've just been making everyone on my teams deal with +1hr builds haha)

**Comment by KaneTW** [comment]
Appreciate the kind words! Yeah, updates on this project have slowed down a bit as we're focused on the hardware. 

Fair warning, there's a bit of bitrot right now when using non-NixOS distros (OpenGL driver stuff), and I think Steam has issues with NixOS occassionally (@georgewsinger knows more about it).

**Comment by jeff-hykin** [comment]
> updates on this project have slowed down a bit as we're focused on the hardware.

I figured. And best of luck on that!

Also no worries about the OpenGL bitrot, I've been using nix on non-nixOS for a while. Some stuff is just outside of what a package manager can do, and I consider that beyond the control of any project.

**Comment by georgewsinger** [comment]
@jeff-hykin Appreciate the kind words.

NixOS isn't perfect, but we think it's the best distro to base Simula off of for a variety of reasons (we'll make a blog post about it when the time is right). We've also noticed a disproportionate number of existing Simula users/fans already use NixOS (about 50%, which is nuts considering how niche NixOS is).

Cheers.

**Comment by jeff-hykin** [comment]
> NixOS isn't perfect

Agreed. I typically don't even recommend nix to others since I have several major criticisms.

> already use NixOS (about 50%

That is absolutely astounding! I wonder why there is such a significant overlap.
