### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by Az-Neter** [SimulaVR/Simula#203]
Did you guys really think leaving the project people actually want to use to die in the water so you can make more ewaste was the proper solution?
By the time you finish your headset, no one will want it because any number of other corps have already surpassed you by decades.

Fix your broken software, that's all anyone cares about. That's all anyone has ever cared about from you.

**Comment by Corallus-Caninus** [comment]
nah this project is awesome. Let me know how I can help.

**Comment by KaneTW** [comment]
Wow, Simula doesn't run on a 68k. Dead project.

You're welcome to:
a) Fund us so we can work on the software. Pure open source software doesn't pay the bills. In 2021, the only option was to make your own hardware. Maybe that's different now, but it's a matter of principle to finish what we started.
b) Port the software to other architectures. This was only tested on x86 and we'll only ever officially support x86 without an incentive to do so.

**Comment by Az-Neter** [comment]
> Wow, Simula doesn't run on a 68k. Dead project.
> 
> You're welcome to:
> a) Fund us so we can work on the software. Pure open source software doesn't pay the bills. In 2021, the only option was to make your own hardware. Maybe that's different now, but it's a matter of principle to finish what we started.
> b) Port the software to other architectures. This was only tested on x86 and we'll only ever officially support x86 without an incentive to do so.

Okay clown, so your project is dead and no one has a reason to use it. 

I'll be sure to inform everyone in the custom HMD space that this is the case, so anyone who stumbles upon this fundraised failure remains far away and without getting their hopes up for you.

How do you know I'm not still waiting on a headset, for Christ's sake?

**Comment by KaneTW** [comment]
If you have a preorder pending, send a refund request with your name/email and order number to refunds@simulavr.com. I couldn't find anything matching your name/s and email address.

I'm not interested in a flame war and you are evidently unable to engage in civil discussion, so you've been blocked from this org.
