### ISSUE TITLE
Minimize the use of default-extensions

### ISSUE THREAD

**Issue by lboklin** [SimulaVR/Simula#30]
The practice of enabling default extensions for all source files is [generally](https://www.reddit.com/r/haskell/comments/5l9w37/listing_extensions_per_hs_or_in_cabal_which_one/) recommended against since it may cause confusion both for the human and the compiler.

Preferably the project would use as few extensions as possible so as to lower the bar of entry for potential contributors.

**Comment by krakrjak** [comment]
I agree, this has always left a sour taste in my mouth. We have had so much other work in front of us that teasing these out has become a back burner thing. I am open to changes along these lines.

**Comment by georgewsinger** [comment]
I'm closing this issue for the time being in an effort to clean up/focus our GitHub Issues on the most important tasks.  In general Simula's codebase is extremely dirty (default-extensions being only a drop in the ocean). This will be addressed when we incorporate Ludvig's PR coming up.
