### ISSUE TITLE
The datatype `Rectangle` is not actually a rectangle

### ISSUE THREAD

**Issue by georgewsinger** [SimulaVR/Simula#4]
The datatype `Rectangle`

```
data Rectangle = Rectangle {
  _rectangleSize :: V2 Int
  } deriving (Show, Eq, Ord)
```

is not actually a rectangle, as opposed to `Rect`:

```
data Rect a = Rect {
  _rectUpperLeft :: V2 a,
  _rectSize :: V2 a
  }
```

which is. This needs refactored.

**Comment by Agnishom** [comment]
How should this be handled?

Do we need the `Rectangle` type at all? Is it being used elsewhere in the code? I think it is good enough to remove that snippet altogether

**Comment by krakrjak** [comment]
Do it! Be the contributor you see in the world. Send a PR and I'll try a build.

**Comment by georgewsinger** [comment]
@Agnishom Welcome to the project. Any build you send over I'll also try.

**Comment by Agnishom** [comment]
I placed a [pull request](https://github.com/SimulaVR/Simula/pull/8). I didn't try building it on my local machine, though.

**Comment by georgewsinger** [comment]
@Agnishom Your pull request leads to a build error. There are still some places in the code that use the (poorly named) `Rectangle` datatype: https://github.com/SimulaVR/Simula/search?utf8=%E2%9C%93&q=Rectangle&type=

**Comment by Agnishom** [comment]
@georgewsinger I fixed those. How about now?

**Comment by georgewsinger** [comment]
@Agnishom I now get the following build error on your pull request:

```
        Ambiguous occurrence ‘Rect’
        It could refer to either ‘Graphics.Rendering.OpenGL.Rect’,
                                 imported from ‘Graphics.Rendering.OpenGL’ at src/Simula/BaseCompositor/OpenGL.hs:13:1-32
                                 (and originally defined in ‘Graphics.Rendering.OpenGL.GL.Rectangles’)
                              or ‘Simula.BaseCompositor.Geometry.Rect’,
                                 imported from ‘Simula.BaseCompositor.Geometry’ at src/Simula/BaseCompositor/OpenGL.hs:16:1-37
                                 (and originally defined
                                    at src/Simula/BaseCompositor/Geometry.hs:(73,1)-(76,3))
```

You should be able to handle these errors yourself before submitting a pull request. Are you able to get the project to build? If you are having trouble, post another GitHub issue and I'll help you get through it.

**Comment by lboklin** [comment]
Issue made obsolete after move to Godot.
