### ISSUE TITLE
What does makeVrCall do?

### ISSUE THREAD

**Issue by georgewsinger** [SimulaVR/Simula#40]
**Problem.** It's not clear what [`makeVrCall`](https://github.com/georgewsinger/simula-openvr/blob/70e8299d24883b0dc60a8142e3585df0aa0407b6/src/OpenVR/TH.hs#L107) is doing to functions in `simula-openvr`. Here is it's truncated definition:

```haskell
makeVrCall :: Name -- ^ function that needs to be converted
           -> String -- ^ new name
           -> Q [Dec]
makeVrCall n s = do
      -- strip the first two arguments
      -- verify that the second arg is Ptr ifTy?
      (VarI _ funTy@(AppT (AppT ArrowT _)
                     (AppT (AppT ArrowT _) resTy)) _) <- reify n
      
      tyDec <- sigD funName (return resTy)

      funDec <- mkFunD resTy
      return [tyDec, funDec]
where
-- ...
```

For example, consider 

```C++
virtual EVRCompositorError Submit( EVREye eEye, const Texture_t *pTexture, const VRTextureBounds_t* pBounds = 0, EVRSubmitFlags nSubmitFlags = Submit_Default ) = 0; //from openvr.h
``` 

This is then converted into `ivrCompositorSubmit_`:

```haskell
-- Internal.chs
{#fun VR_IVRCompositor_FnTable->Submit as ivrCompositorSubmit_
      { coerce `VR_IVRCompositor_FnTable'
      , castPtr `Ptr VR_IVRCompositor_FnTable'
      , `EVREye'
      , `TexturePtr'
      , `VRTextureBounds_t'
, `EVRSubmitFlags' } -> `EVRCompositorError' #}
```

which is finally passed through `makeVrCall`:

```haskell
-- Interface.hs
makeVrCall 'ivrCompositorSubmit_ "ivrCompositorSubmit" 
```

What is the new type/expansion of `ivrCompositorSubmit`? (This is not retrievable from GHCi due to [this issue](https://github.com/SimulaVR/Simula/issues/36); moreover, searching `.stack-work` for `find . -name "*splice*"` doesn't yield any TH expansion files after compiling with stack).

**Comment by KaneTW** [comment]
`makeVrCall` removes the first two arguments that 

* Provide the pointer to the function table
* Simulate C++ calling convention (where the 1st argument is the `this` pointer)

since they're static throughout program invocation (technically, after `vrInit`. reader monad would be better here instead of the global data i have)


The type of `ivrCompositorSubmit` is `EVREye -> ... -> IO EVRCompositorError`, with the first two arguments removed (they're supplied internally).

I believe Haddock docs should still work. `stack haddock` generates haddock docks in .stack-work somewhere

**Comment by georgewsinger** [comment]
So using the notation

```haskell
{#fun VR_IVRCompositor_FnTable->WaitGetPoses as ivrCompositorWaitGetPoses_
      { coerce `VR_IVRCompositor_FnTable'         -- vtable_p (points to vtable implicitly stored bare in IVRCompositor C++ class)
      , castPtr `Ptr VR_IVRCompositor_FnTable'    -- vpointer_p_p (points to vtable_p)
      , id `TrackedDevicePosePtr'
      , `Int'
      , id `TrackedDevicePosePtr'
      , `Int' } -> `EVRCompositorError' #}
```

we have that 

```haskell
makeVrCall 'ivrCompositorSubmit_ "ivrCompositorSubmit" 
```

creates a function `ivrCompositorSubmit` that automatically jams values for `vtable_p` and `vpointer_p_p` into the first two arguments of `ivrCompositorSubmit_`. Are `vtable_p` and `vpointer_p_p` stored globally somewhere in the code?

**Comment by KaneTW** [comment]
Yeah. `openVRContext :: MVar OpenVRContext` in Interface.hs stores a data type with all `vpointer_p_p`

**Comment by lboklin** [comment]
Issue made obsolete after moving to Godot Engine.
