### ISSUE TITLE
Windows enter "superposition" stutter while dragging

### ISSUE THREAD

**Issue by jniedrauer** [SimulaVR/Simula#46]
When a window is dragged, it appears to rapidly flash between the two points, possibly once per frame. Sometimes one of the two positions is rendered more frequently than the other, but they are never visible at the same time. As the window is moved further, the two points diverge from each other, but not predictably. It seems that position updates are only sent to each of the two positions while the window is visible at that position.

Occasionally, the stuttering will stop. When this happens, the window will snap to a third position approximately in the middle of the original two.

While the window is flashing, I am unable to release it using the grip button on the Vive controller. Once it stops flashing, I am able to release it.

Reproduced on:
simula: ac8eb96270f967603f661b16d1a11c4f30632643
stack: Version 1.7.1, Git revision 681c800873816c022739ca7ed14755e85a579565 (5807 commits) x86_64 hpack-0.28.2
weston: 3.0.0
nvidia driver: akmod-nvidia-396.54-1.fc28.x86_64
HMD: HTC Vive

**Comment by lboklin** [comment]
This was fixed in 914a481
