### ISSUE TITLE
A way to resize windows (not scaling)

### ISSUE THREAD

**Issue by lboklin** [SimulaVR/Simula#47]
Currently one can only resize the window by changing the scale (uniformly in all directions), but this does not help when you want to change the extents of the window surface without also changing the scale of the content.

This is critical to usability.

**Comment by georgewsinger** [comment]
This could be as simple as invoking the proper weston (or wlroots) call and placing it in our own sprite resizing handler. See i.e. [here](https://github.com/swaywm/wlroots/blob/e61ea7706b36435836f341bc371124902d5fb412/rootston/desktop.c#L168).
