### ISSUE TITLE
Support for special character input

### ISSUE THREAD

**Issue by lboklin** [SimulaVR/Simula#52]
A must-have for any use case. Right now alphanumeric characters work along with modifier keys, but special characters (such as ~) do not.

**Comment by lboklin** [comment]
After taking some time looking at this it seems to me that the issue is that we're attempting to translate Godot's high-level key codes into [evdev's lower-level event codes](https://gitlab.freedesktop.org/libevdev/libevdev/blob/master/include/linux/input-event-codes.h), which apparently does not cover non-hardware keys, ie. symbols produced via modifier keys (at least that's the only pattern I've been able to discern).

We're going to have to either use some higher-level parts of libweston which takes care of input mapping for us, or we're going to have to write something ourselves. In any case it's more work than simply adding to the existing key translation map.

**Comment by georgewsinger** [comment]
**Vim Test.**
1. **Symbols that don't work.**
   - `~`
   - `KP_0, …, KP_9`
   - `KP_PERIOD`
   - `[`
   - `]`
   - `{`
   - `}`
   - `/`
2. **Symbols that not only don't work but exhibit weird behavior when pressed.**
   - `#`
   - `?`
   - `$`
   - `<`
   - `>`
3. **Symbols that I'm not sure about.**
   - `Alt + *`

Everything else seems to work (including, for example, `Ctrl + *` combos and the remaining `KP_*` combinations).

**Comment by lboklin** [comment]
Fixed in fa56e8f
