### ISSUE TITLE
Getting rid of window decorations and shadow effects

### ISSUE THREAD

**Issue by lboklin** [SimulaVR/Simula#63]
At least in VR there's no need for window decorations (we will want our own solution that makes more sense for VR), so it would be good to see about removing anything but the actual contents of the window. 

I know this is a bit tricky when it comes to CSD (client side decorations) since that's handled directly by the application, so not sure we can do much about those, but the SSD (server side decorations) should be manageable unless that's part of Weston itself, in which case we'd have to fork it?

**Comment by georgewsinger** [comment]
Right now we have no window decorations on XDG apps, but still have window decorations on XWayland apps.
