### ISSUE TITLE
Binary distribution format

### ISSUE THREAD

**Issue by lboklin** [SimulaVR/Simula#64]
Need to figure out a way to distribute the application for testing (and future packaging) without making the tester compile everything perself or installing/compiling 9 241 dependencies (although hopefully we can keep our dependencies lower than that).

Options:
1. Static compilation. This would be the most preferable option, but GHC makes this very hard and Stack isn't very interested in helping. Searching for static compilation of a Haskell project will give you a headache. Best lead I got talked about using an Alpine Linux Docker image with a special build of GHC.
2. Ship the binary together with all deps bundled internally. Neither elegant nor efficient.
3. Nix package. If we can make this work that would be an elegant solution, but since we depend on mesa we're going to be affected by https://github.com/NixOS/nixpkgs/issues/9415 
4. Flatpak - https://szibele.com/stakpak-flatpak-a-haskell-stack-app-into-flathub/
5. AppImage?

**Comment by georgewsinger** [comment]
- (1) looks to be infeasible as far as I can tell.
- (2) looks like a nightmare.
- (3) is the most elegant but probably also infeasible. I spent a lot of time trying to do this with Simula v0 and eventually gave up. Perhaps Godot makes things easier.
- (4) and (5) I haven't looked into.

Another option (6) might be to make distro specific builds of Simula for Ubuntu & Arch.

**Comment by georgewsinger** [comment]
I'm unable to get Simula to build with `--nix` due to the infamous `c2hs: Simula/WaylandServer.chi not found` error.  I'm triaging this for now until we get wlroots incorporated into Simula (which should completely eliminate the need for `simula-wayland` all together).
