### ISSUE TITLE
Simula Requires run.sh to Launch on Ubuntu Bionic

### ISSUE THREAD

**Issue by georgewsinger** [SimulaVR/Simula#66]
Launching Simula directly (via `godot --path $(GODOTPROJECT)`) fails work for me on Ubuntu, and hence `make run` fails to launch Simula (more precisely, it fails to launch Simula in VR mode and instead only launches Simula in pancake mode).  Launching Simula via `~/.steam/ubuntu12_32/steam-runtime/run.sh godot --path $(GODOTPROJECT)` does work, yet this is evidently not the case for everyone.

I would propose that we modify `./addons/godot-haskell-project/Makefile` to

```
run:
        stack --verbosity=error build godot-haskell-plugin $$TELEMETRY
        cp $(LIBFILE) $(PROJECTROOT)
        ~/.steam/ubuntu12_32/steam-runtime/run.sh godot --path $(GODOTPROJECT)
```

but ` ~/.steam/ubuntu12_32/steam-runtime/run.sh` is not the same for everyone. Our Makefile should detect the location of `run.sh` and launch accordingly.

**Comment by lboklin** [comment]
As far as I know, `run.sh`s possible locations are
```
~/.steam/{,steam/}ubuntu12_32/steam-runtime/run.sh
```
