### ISSUE TITLE
strictness

### ISSUE THREAD

**Issue by Cipherwraith** [SimulaVR/Simula#7]
Why doesnt the project force thunks to evaluate when possible instead of allowing the laziness to build endless thunks?

**Comment by krakrjak** [comment]
Neither happens. Haskell code gets called by c code and vice versa. Why would we force what is not needed to be forced?

**Comment by georgewsinger** [comment]
@Cipherwraith welcome to the project.  Are you asking why we don't use more GHC strictness annotations and/or pragmas?

It's possible those will need to be used in the future. Right now we're focused on getting a working prototype from which performance issues can be benchmarked and selectively addressed.

If there's a certain part of the code that you think might be bottlenecking things let me know. As @krakrjak also pointed out, we're using lots of C calls in this project also.
