### ISSUE TITLE
Support OpenHMD

### ISSUE THREAD

**Issue by lboklin** [SimulaVR/Simula#72]
We don't want to be tied to Valve's unfree Vive drivers and OpenVR implementation, so it would be preferable if Simula worked out of the box using the only reasonable FLO alternative: [OpenHMD](https://github.com/OpenHMD/OpenHMD).  

Blockers:

- [ ] The [OpenHMD plugin](https://github.com/GodotVR/godot_openhmd) for Godot does not work with multi-threading: https://github.com/GodotVR/godot_openhmd/issues/27. This makes it impossible to run Simula with OpenHMD.

Lacking features:

- [ ] It doesn't have fully featured support for Vive controllers (see https://github.com/GodotVR/godot_openhmd/issues/6 and https://github.com/OpenHMD/OpenHMD/issues/119). It [should](https://github.com/SimulaVR/Simula/issues/53) however be possible to use Simula without VR controllers.

- [ ] No support for positional tracking, only rotational (see [device support table](https://github.com/OpenHMD/OpenHMD/wiki/Support-List)). May cause discomfort when looking around.

- [ ] No support for direct rendering, so the user must resort to using extended desktop.

**Comment by georgewsinger** [comment]
Is there any update on this? I believe we have disabled Godot multithreading for the time being, which might help us get around the first blocker.

**Comment by lboklin** [comment]
Simula no longer requires multithreading?

**Comment by georgewsinger** [comment]
We had to disable it to fix a texturing error race condition (textures were showing up as black).
