### ISSUE TITLE
Prioritize use case: VR application/game development in VR

### ISSUE THREAD

**Issue by lboklin** [SimulaVR/Simula#78]
For general desktop productivity, it may be hard to convince a user to put their HMD on and do their work from inside Simula only to take it off out of discomfort (as well as possible eye-strain) after about an hour because of the weight and form factor of current HMD headsets. 

Until a time when HMDs can be comfortably worn throughout an entire (work) day I propose Simula focus on a more practical and narrow use case, namely VR development. 

Putting on and taking off the HMD over and over again to test your VR application gets old really fast, especially if you (like me) wear glasses. Leaving the HMD on as you jump back and forth between coding and testing would be a big improvement.

This narrows the scope in the short term but is not trivial. Core features (besides the obvious compositor stuff) include:

- [ ] Switching between VR applications (Simula <-> Your VR app)
- [ ] Pausing Simula, retaining the full state of it and all applications running in it.
- [ ] Pausing or exiting and resuming the other VR app after switching to Simula
- [ ] Killing the other VR app in case it misbehaves 

Bonus/extra features:
- [ ] Use Simula as an overlay (like the SteamVR dashboard) so you don't even have to exit your VR application.

This will effectively replace SteamVR Home, but we also don't want to be tied down to just OpenVR so a general solution (or implementations for each API) would be best.

Simula could even become the defacto Godot VR-development environment if one makes use of Godot-specific features such as live scripting (hot-loading scripts) and live scene editing. This could content with the other big game engines' own similar attempts. It would also help promote using free software to develop VR apps.

**Comment by georgewsinger** [comment]
- Agree with the general direction of this (at the very least: seeing if Godot developers are interested in Simula should be one of the earliest tests we run once we fix the basic usability issues).
- `godot-wayland` is the first step in this direction, no?
- Is there anything in principle that prevents us from simultaneously running SteamVR apps (especially useful ones like Tilt Brush) alongside Simula (ideally SteamVR apps would be "minimized" in/contained within Simula)?
