### ISSUE TITLE
Port to AARCH64 (RasPi 4)

### ISSUE THREAD

**Issue by nuess0r** [SimulaVR/Simula#80]
Hi

This is very much a midterm/longterm whish/idea for this nice project and to push you a little bit towards your own goals ;-)
> In the long-run, this means allowing people to run Linux in standalone AR & VR HMDs

Would be nice if Simula would be ported to AARCH64 (64 bit ARM).
What are the blocking points at the moment for this?

The newly announced RasPi 4 offers two independent HDMI outputs which can support both 4k resolutions. This lowers the barrier a lot to make a DIY stand alone Linux HMD.

I guess, that for this OpenHMD support is essential (#72) which needs quite a lot of effort on there side to make it happen for Simula

**Comment by KaneTW** [comment]
Not too much apart from OpenHMD. GHC runs on arm64, pretty sure Godot runs on arm64, and the one hack I had to do that depends on x64 calling conventions can be adapted.

**Comment by georgewsinger** [comment]
This is a good idea, but I'm closing this issue for now while we focus on getting non-standalone VR up & running.  When we get to this milestone I'll re-open.
