### ISSUE TITLE
Making Simula usable without a Vive controller

### ISSUE THREAD

**Issue by georgewsinger** [SimulaVR/Simula#95]
**Using the Vive controller for inputs is inefficient.** @NerveCoordinator feedback:

> a google search requires
> 
>   - pick up controller, point at firefox
>   - click in the tiny little search bar
>   - set down controller, type
>   - pick up controller again
> 
> … extremely inefficient,

**Proposal.** Here is a proposed way that we can integrate traditional mouse & keyboard usage into Simula. Let `MOD` be a modifier key (e.g. `Ctrl`, `Alt`, etc). Here are some controls we could add to Simula:

1.  **Place a mouse pointer on the window being stared at.** Stare at a window and press and release `MOD`; the window will be activated and have a pointer placed at the location of user's gaze. Once placed, the pointer can be used as usual with a mouse (movement, left-click, right-click, drag and drop, etc), but will be movement-bounded for now by the window's boundary.
2.  **Orient a window towards the user's gaze.** Stare at a window and press `MOD + w`.
3.  **Quickly left-click on a window being stared at.** Stare at a window and press `MOD + l`.
4.  **Move a window backwards/forwards.** Stare at the window and, while holding down `MOD`, scroll up or down on the mouse wheel.
5.  **Manipulate a window around its sphere.** Stare at the window and, while holding down `MOD + m`, orient your gaze towards where you want the window placed in the sphere surrounding your current world position.

Eventually, we could make these bindings alterable with a configuration file.

**Comment by lboklin** [comment]
Quick reflection: Controlling the pointer through neck movements is imprecise and will cause neck strain. Eye-tracking would be good for this though. Controlling the pointer with your mouse once a window is focused is a potential solution.

**Comment by georgewsinger** [comment]
@lboklin Agreed: (1) allows us to place a mouse pointer in a window, which can then be controller by the PC mouse.

**Comment by georgewsinger** [comment]
**Mouse handling: Godot vs. wlroots.** The biggest question for me right now is how to make Godot's normal mouse handling (when you e.g. move the mouse accross the Godot pancake mode) play well with our new wlroots cursor handling. Some questions:

  - Should we intercept mouse movements with Godot, and then pass them off to wlroots?
  - Or should we turn off the mouse handling entirely within Godot, and have wlroots do everything for us?
      - See [Input.set_mousemode](https://docs.godotengine.org/en/3.1/classes/class_input.html#enum-input-mousemode) for possible useful functionality.

In either case: if the user passes the mouse into Simula (the pancake window), it looks like the new behavior is going to be that Simula will "swallow the cursor" (in the sense that users won't be able to just move the mouse out of the pancake bounds like normal). Is this a problem? If so: how should users be able to get their OS cursor back?

**Comment by georgewsinger** [comment]
:seedling: Passed this off to [/r/godot](https://www.reddit.com/r/godot/comments/e4p60r/mouse_handling_in_a_godot_window_managercompositor/)
